### ISSUE TITLE
Embed Imagemagick binary

### ISSUE THREAD

**Issue by ad-si** [ad-si/Perspec#1]
Possible solutions:

- https://stackoverflow.com/q/16007654/1850340
- https://blog.schdbr.de/imagemagic-osx-static-relocatable-build
    ```sh
    brew install imagemagick \
      --without-modules \
      --without-freetype \
      --without-libtiff \
      --with-zero-configuration
    cp /usr/local/bin/convert app-aux-files/convert
    chmod 755 app-aux-files/convert
    ```
    Set `convertBin = "./convert"` in app/Main.hs 
    and build the core binary with stack install.
- https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=13145&hilit=static+Mac&sid=dc6ddd4cd1629cf7935e21e9b473b400&start=15

**Comment by haydenflinner** [comment]
Why not humbly suggest `conda install imagemagick`? I think you will have a hard time bundling imagemagick for all platforms

**Comment by ad-si** [comment]
@haydenflinner As far as I can tell, all Python bindings of ImageMagick also depend on a global installation and don't include a binary. 😞

**Comment by ad-si** [comment]
I played around some more and in the end it was easier as expected. I just had to set 2 environment variables 😅.

```hs
setEnv "MAGICK_HOME" (currentDir ++ "/imagemagick")
setEnv "DYLD_LIBRARY_PATH" (currentDir ++ "/imagemagick/lib")
```

Fixed in 4df8c84.

**Comment by haydenflinner** [comment]
Sorry, didn't realize you were targeting a mac app and not just a general library, hell I thought the project was in Python lol. But btw, you forgot to check the box on your README todo :-)
